[package]
name = "ec"
version = "0.1.1"
edition = "2021"
description = "A systems level compiler for the English language"

[dependencies]
thiserror = "1.0"

[profile.release]
opt-level = 3
lto = true
